kafka.bootstrap.servers=kafka:9092
kafka.topic=test-topic
elasticsearch.hosts=elasticsearch:9200
elasticsearch.index=test-index

# Bulk processing configuration
elasticsearch.batch.size=10
elasticsearch.flush.interval.ms=1000
